/**
 * Copyright (c) 2019 kxjl All Rights Reserved.
 * 
 * This software license agreement (the "Agreement") is a legal agreement between the user 
 * ("You" or the "User") and kxjl ("kxjl") 
 * for the software products (the "Software") and related services (the "Service") that 
 * accompanies this Agreement, as may be updated or replaced by feature enhancements, 
 * updates or maintenance releases and any services that may be provided by kxjl under this Agreement. 
 * You are not allowed to download, install or use the Software or to use Services unless 
 * you accept all the terms and conditions of this Agreement. Your downloading, 
 * installation and use of the Software shall be regarded as your acceptance of the Agreement 
 * and your agreement to be bound by all the terms and conditions of this Agreement.
 * 
 * The above notice shall be included in all copies or substantial portions of the Software.
 * 
 * The software is provided "as is", without warranty of any kind, express or implied, 
 * including but not limited to the warranties of merchantability, fitness for a particular 
 * purpose and noninfringement. In no event shall the authors or copyright holders be 
 * liable for any claim, damages or other liability, whether in an action of contract, 
 * tort or otherwise, arising from, out of or in connection with the software or the use 
 * or other dealings in the software.
 */
package com.kxjl.admin.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.kxjl.admin.persistence.entity.KgDirTreeExample;
import com.kxjl.admin.persistence.entity.KgDirTreeKey;
import com.kxjl.admin.persistence.entity.KgEditClass;
import com.kxjl.admin.persistence.entity.KgEditData;
import com.kxjl.admin.persistence.entity.KgEditDirTree;
import com.kxjl.admin.persistence.entity.KgEntity;
import com.kxjl.admin.persistence.entity.KgEntityKey;
import com.kxjl.admin.persistence.entity.KgTags;
import com.kxjl.admin.persistence.entity.KgClass;
import com.kxjl.admin.persistence.entity.KgDataLog;
import com.kxjl.admin.persistence.entity.KgDirTree;
import com.kxjl.admin.service.KgDirTreeService;
import com.kxjl.admin.service.KgEditDataService;
import com.kxjl.admin.service.KgEditDirTreeService;
import com.kxjl.admin.service.KgObjectSubGroupService;
import com.alibaba.fastjson.JSONObject;
import com.kxjl.admin.common.Pagination;
import com.kxjl.admin.common.WZResponseEntity;
import com.kxjl.admin.common.LoginUser;
import com.kxjl.base.util.UUIDUtil;
import com.kxjl.admin.util.Constants;
import com.kxjl.admin.util.Page;
import com.kxjl.admin.util.PageUtil;
import com.kxjl.admin.persistence.adapter.dao.KgDataLogMapperAdapter;
import com.kxjl.admin.persistence.adapter.dao.KgDirTreeMapperAdapter;
import com.kxjl.admin.persistence.adapter.dao.KgEditDataMapperAdapter;
import com.kxjl.admin.persistence.adapter.dao.KgEditDirTreeMapperAdapter;
import com.kxjl.admin.persistence.dao.KgDirTreeMapper;

/**
 * autoGenerated
 * 
 * @date 2020年06月08日 11:50:55
 * @author Generator
 */
@Service("kgDirTreeService")
public class KgDirTreeServiceImpl implements KgDirTreeService {

	@Autowired
	KgDirTreeMapperAdapter kgDirTreeMapper;

	@Autowired
	KgObjectSubGroupService kgObjectSubGroupService;

	@Autowired
	KgEditDirTreeService kgEditDirTreeService;

	@Autowired
	KgEditDataMapperAdapter kgEditDataMapperAdapter;

	@Autowired
	KgEditDirTreeMapperAdapter kgEditDirTreeMapperAdapter;

	@Autowired
	KgDataLogMapperAdapter kgDataLogMapperAdapter;

	@Autowired
	KgEditDataService kgEditDataService;

	/**
	 * <p>
	 * New Info
	 * </p>
	 * 
	 * @param kgDirTree
	 * @return
	 */
	@Transactional
	public WZResponseEntity<?> add(LoginUser user, KgDirTree kgDirTree) {

		WZResponseEntity<?> rst = new WZResponseEntity<>();

		if (kgDirTree.getId() == null || kgDirTree.getId().equals(""))
			kgDirTree.setId(UUIDUtil.get32UUID());

		if (kgDirTree.getVersionId() == null || kgDirTree.getVersionId().equals(""))
			kgDirTree.setVersionId("1.0.0");

		if (kgDirTree.getParDirId() == null || kgDirTree.getParDirId().equals("")) {

			kgDirTree.setParDirId("0");

		}

		KgDirTree tp = selectByName(kgDirTree);
		if (tp != null && !tp.getId().equals(kgDirTree.getId())) {
			rst.setIsSuccess(false);
			rst.setErrorMsg("名称重复!");
		} else {

			if (user != null && user.getRoleId().contains(Constants.DEFAULT_ADMIN_ROLEID)) {

				kgDirTree.setSubIds(kgDirTree.getDirId());
				kgDirTree.setDirId("");
				// 处理领域
				kgObjectSubGroupService.resetObjectSubGroupAttr(kgDirTree.getId(), kgDirTree.getSubIds(), "3");

				boolean isOk = kgDirTreeMapper.insertSelective(kgDirTree) > 0;

				rst.setIsSuccess(isOk);

			} else {
				KgEditDirTree data = new KgEditDirTree(kgDirTree);
				// data.setId(UUIDUtil.get32UUID());
				data.setId(kgDirTree.getId());
				return kgEditDirTreeService.add(user, data);
			}

		}

		return rst;

	}

	public KgDirTree selectByName(KgDirTree kgDirTree) {

		if (kgDirTree.getDirName() == null || kgDirTree.getDirName().equals(""))
			return null;

		KgDirTree rst = null;

		KgDirTree query = new KgDirTree();
		query.setDirName(kgDirTree.getDirName());
		query.setFullNameQuery("true");
		List<KgDirTree> lst = kgDirTreeMapper.selectList(query);

		if (lst != null && lst.size() > 0)
			rst = lst.get(0);

		return rst;

	}

	/**
	 * <p>
	 * Modify Info
	 * </p>
	 * 
	 * @param kgDirTree
	 * @return
	 */
	@Transactional
	public WZResponseEntity<?> modify(LoginUser user, KgDirTree kgDirTree) {

		WZResponseEntity<?> rst = new WZResponseEntity<>();

		if (kgDirTree.getParDirId() == null || kgDirTree.getParDirId().equals("")) {

			kgDirTree.setParDirId("0");

		}

		KgDirTree tp = selectByName(kgDirTree);
		if (tp != null && !tp.getId().equals(kgDirTree.getId())) {
			rst.setIsSuccess(false);
			rst.setErrorMsg("名称重复!");
		} else {

			if (user != null && user.getRoleId().contains(Constants.DEFAULT_ADMIN_ROLEID)) {

				kgDirTree.setSubIds(kgDirTree.getDirId());
				kgDirTree.setDirId("");
				// 处理领域
				kgObjectSubGroupService.resetObjectSubGroupAttr(kgDirTree.getId(), kgDirTree.getSubIds(), "3");

				boolean isok = kgDirTreeMapper.updateByPrimaryKeySelective(kgDirTree) > 0;
				rst.setIsSuccess(isok);
			} else {
				return kgEditDirTreeService.modify(user, new KgEditDirTree(kgDirTree));
			}
		}

		return rst;
	}

	/**
	 * <p>
	 * Delete
	 * </p>
	 * 
	 * @param id
	 * @return
	 */
	/**
	 * <p>
	 * Delete
	 * </p>
	 * 
	 * @param id
	 * @return
	 */
	@Transactional
	public Boolean delete(LoginUser user, String id, String version) {
		if (user != null && user.getRoleId().contains(Constants.DEFAULT_ADMIN_ROLEID)) {

			return deleteData(id, version);
		} else {
			return kgEditDirTreeService.delete(user, id);
		}

	}

	private Boolean deleteData(String id, String version) {
		if (id.contains(",")) {
			String[] ids = id.split(",");
			for (String tid : ids) {
				KgDirTree tp = getOne(tid, version);
				tp.setDeleted("1");// 1删除
				kgDirTreeMapper.updateByPrimaryKey(tp);

			}
			return true;
		} else {
			KgDirTree tp = getOne(id, version);
			if (tp != null) {
				tp.setDeleted("1");// 1删除

				return kgDirTreeMapper.updateByPrimaryKey(tp) > 0 ? true : false;
			}
			return true;
		}

	}

	/**
	 * <p>
	 * query info by id
	 * </p>
	 * 
	 * @param id
	 * @return
	 */
	@Transactional(readOnly = true)
	public KgDirTree getOne(String id, String version) {

		KgDirTree cur = null;

		KgDirTree key = new KgDirTree();
		key.setId(id);
		key.setVersionId(version);

		List<KgDirTree> lst = kgDirTreeMapper.selectList(key);
		if (lst != null && lst.size() > 0)
			cur = lst.get(0);

		return cur;
	}

	/**
	 * <p>
	 * query all info
	 * </p>
	 * 
	 * @return
	 */
	@Transactional(readOnly = true)
	public List<KgDirTree> getAll() {
		KgDirTreeExample example = new KgDirTreeExample();
		return kgDirTreeMapper.selectByExample(example);
	}

	/**
	 * 增加查询列表改动标记
	 * 
	 * @param user
	 * @param lst
	 * @author:kxjl
	 * @date 2020年8月6日
	 */
	private void addDiffFlag(LoginUser user, List<KgDirTree> lst) {
		// 增加修改标记
		KgEditData equery = new KgEditData();
		equery.setEditUser(user.getUserId());
		equery.setAuditState("1");// 未提交
		List<KgEditData> edatas = kgEditDataMapperAdapter.selectList(equery);

		KgEditData equery2 = new KgEditData();
		equery2.setEditUser(user.getUserId());
		equery2.setAuditState("2");// 未提交
		List<KgEditData> edataAudits = kgEditDataMapperAdapter.selectList(equery2);

		JSONObject jedit = new JSONObject();

		for (KgDirTree data : lst) {
			for (KgEditData eitem : edatas) {
				if (data.getId().equals(eitem.getEditOriDataId()) || data.getId().equals(eitem.getEditDataId())) {

					jedit.put("editAction", eitem.getEditAction());
					jedit.put("auditState", "1");
					jedit.put("editDataId", eitem.getEditDataId());
					data.setMyEdit(jedit.toJSONString());

					// data.setMyEdit(eitem.getEditAction() + ":" + eitem.getEditDataId());
				}
			}

			for (KgEditData eitem : edataAudits) {
				if (data.getId().equals(eitem.getEditOriDataId()) || data.getId().equals(eitem.getEditDataId())) {
					jedit.put("editAction", eitem.getEditAction());
					jedit.put("auditState", "2");
					jedit.put("editDataId", eitem.getEditDataId());
					data.setMyEdit(jedit.toJSONString());
				}

				// data.setMyEdit("4:" + eitem.getEditDataId());
			}

		}

	}

	private KgDirTree selectByFullName(LoginUser user, String name) {
		KgDirTree q = new KgDirTree();
		q.setDirName(name);
		q.setFullNameQuery("true");

		KgDirTree data = null;
		List<KgDirTree> lst = kgDirTreeMapper.selectList(q);
		if (lst != null && lst.size() > 0)
			data = lst.get(0);

		return data;
	}

	/**
	 * 
	 * @param example
	 * @return
	 * @author:kxjl
	 * @date 2020年6月9日
	 */
	public Page<KgDirTree> selectList(LoginUser user, KgDirTree query, Pagination pageCondition) {
		com.github.pagehelper.Page pageinfo = PageUtil.getPage(pageCondition);

		query.setCurUser(user.getUserId());
		List<KgDirTree> lst = kgDirTreeMapper.selectList(query);

		if (query.getDirName() != null) {

			// 增加其他相关查询
			KgDirTree kfullName = selectByFullName(user, query.getDirName());
			// 存在指定名称
			if (kfullName != null) {
				// 数据排序到第一，或者添加到第一位
				int index = 0;
				boolean find = false;
				for (int i = 0; i < lst.size(); i++) {
					if (lst.get(i).getId().equals(kfullName.getId())) {
						index = i;
						find = true;
						break;
					}
				}

				if (index != 0 && find) {
					lst.add(0, lst.remove(index));
				}

				if (!find) {
					lst.add(0, kfullName);
				}
			}

		}

		addDiffFlag(user, lst);

		Page<KgDirTree> page = new Page<KgDirTree>();
		page.setResults(lst);
		page.setPageNo(pageinfo.getPageNum());
		page.setPageSize(pageinfo.getPageSize());
		page.setTotalRecord((int) pageinfo.getTotal());

		return page;
	}

	/**
	 * 获取指定cls的下级cls
	 * 
	 * @param node
	 * @return
	 * @author:kxjl
	 * @date 2020年6月18日
	 */
	public List<KgDirTree> getTreeData(LoginUser user, KgDirTree node) {
		node.setCurUser(user.getUserId());
		List<KgDirTree> lst = kgDirTreeMapper.getTreeData(node);

		addDiffFlag(user, lst);

		return lst;

	}

	@Transactional
	public WZResponseEntity<?> audit(LoginUser user, KgDirTree kgItem, KgEditData editData) {

		WZResponseEntity<?> rst = new WZResponseEntity<>();

		String auditRstId = "";// 当前审核合并后的数据id,也存到 对应的edit表中.
		if (editData.getAuditState().equals("5")) // 不通过
		{

		} else if (editData.getAuditState().equals("3") || editData.getAuditState().equals("4")) // 通过
		{

			KgDirTree olddata = getOne(kgItem.getId(), Constants.DEFULT_VERSION);

			// 多人修改,并且多个人全部为删除操作，则最后删除
			if (editData.getEditAction().contains(",")) {
				String[] actions = editData.getEditAction().split(",");
				boolean alldelete = true;
				for (String ac : actions) {
					if (!ac.equals("3")) {
						alldelete = false;
						break;
					}
				}
				if (alldelete) {
					deleteData(editData.getEditOriDataId(), Constants.DEFULT_VERSION);
				}

			}

			// 修改真实数据
			if (editData.getEditAction().equals("3"))// 单人删除
			{
				deleteData(editData.getEditOriDataId(), Constants.DEFULT_VERSION);
			} else if (editData.getEditAction().equals("1"))// 单人新增
			{

				rst = add(user, kgItem);
				if (!rst.getIsSuccess())
					return rst;
			} else // 合并修改，只要有一个人不删除，均按修改操作
			{
				rst = modify(user, kgItem);
				if (!rst.getIsSuccess())
					return rst;
			}

			// 保存当前审核结果数据备份，包括删除的
			KgDirTree auditRst = getOne(kgItem.getId(), Constants.DEFULT_VERSION);
			if (auditRst != null) {

				KgEditDirTree edata = new KgEditDirTree(auditRst);
				auditRstId = UUIDUtil.get32UUID();
				edata.setId(auditRstId);
				kgEditDirTreeService.addtionData(edata);
				kgEditDirTreeMapperAdapter.insertSelective(edata);

			} else {
				// 保存删除的快照
				KgEditDirTree eolddata = new KgEditDirTree(olddata);
				auditRstId = UUIDUtil.get32UUID();
				eolddata.setId(auditRstId);
				eolddata.setDeleted("0");
				kgEditDirTreeService.addtionData(eolddata);
				kgEditDirTreeMapperAdapter.insertSelective(eolddata);
			}

			// 保存快照数据id
			editData.setAuditRstId(auditRstId);

			String idold = "";
			if (olddata != null) {
				// 保存编辑前数据备份-》edit表
				KgEditDirTree eolddata = new KgEditDirTree(olddata);
				idold = UUIDUtil.get32UUID();
				eolddata.setId(idold);
				kgEditDirTreeService.addtionData(eolddata);
				kgEditDirTreeMapperAdapter.insertSelective(eolddata);
			}

			// 记录数据修改日志
			KgDataLog dlog = new KgDataLog();
			dlog.setId(UUIDUtil.get32UUID());
			dlog.setAuditUser(user.getUserId());
			dlog.setDataId(kgItem.getId());
			dlog.setDataType("2");
			dlog.setEditAction(editData.getEditAction());
			dlog.setEditUser(editData.getEditUser());
			dlog.setEditUserName(editData.getEditUserName());

			// 记录对应备份的数据id
			dlog.setEditDataPre(idold);
			dlog.setEditDataNext(auditRstId);

			kgDataLogMapperAdapter.insertSelective(dlog);

		}

		// 修改审核数据
		kgEditDataService.audit(user, editData);

		rst.setIsSuccess(true);

		return rst;
	}

}