/**
 * Copyright (c) 2019 kxjl All Rights Reserved.
 * 
 * This software license agreement (the "Agreement") is a legal agreement between the user 
 * ("You" or the "User") and kxjl ("kxjl") 
 * for the software products (the "Software") and related services (the "Service") that 
 * accompanies this Agreement, as may be updated or replaced by feature enhancements, 
 * updates or maintenance releases and any services that may be provided by kxjl under this Agreement. 
 * You are not allowed to download, install or use the Software or to use Services unless 
 * you accept all the terms and conditions of this Agreement. Your downloading, 
 * installation and use of the Software shall be regarded as your acceptance of the Agreement 
 * and your agreement to be bound by all the terms and conditions of this Agreement.
 * 
 * The above notice shall be included in all copies or substantial portions of the Software.
 * 
 * The software is provided "as is", without warranty of any kind, express or implied, 
 * including but not limited to the warranties of merchantability, fitness for a particular 
 * purpose and noninfringement. In no event shall the authors or copyright holders be 
 * liable for any claim, damages or other liability, whether in an action of contract, 
 * tort or otherwise, arising from, out of or in connection with the software or the use 
 * or other dealings in the software.
 */
package com.kxjl.admin.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.kxjl.admin.persistence.entity.KgSubGroupExample;
import com.kxjl.admin.persistence.entity.KgSubGroupKey;
import com.kxjl.admin.persistence.entity.KgClass;
import com.kxjl.admin.persistence.entity.KgDataLog;
import com.kxjl.admin.persistence.entity.KgEditData;
import com.kxjl.admin.persistence.entity.KgEditSubGroup;
import com.kxjl.admin.persistence.entity.KgEntity;
import com.kxjl.admin.persistence.entity.KgProperty;
import com.kxjl.admin.persistence.entity.KgSubGroup;
import com.kxjl.admin.service.KgEditDataService;
import com.kxjl.admin.service.KgEditSubGroupService;
import com.kxjl.admin.service.KgSubGroupService;
import com.alibaba.fastjson.JSONObject;
import com.kxjl.admin.common.Pagination;
import com.kxjl.admin.common.WZResponseEntity;
import com.kxjl.admin.common.LoginUser;
import com.kxjl.base.util.UUIDUtil;
import com.kxjl.admin.util.Constants;
import com.kxjl.admin.util.Page;
import com.kxjl.admin.util.PageUtil;
import com.kxjl.admin.persistence.adapter.dao.KgDataLogMapperAdapter;
import com.kxjl.admin.persistence.adapter.dao.KgEditDataMapperAdapter;
import com.kxjl.admin.persistence.adapter.dao.KgEditSubGroupMapperAdapter;
import com.kxjl.admin.persistence.adapter.dao.KgSubGroupMapperAdapter;
import com.kxjl.admin.persistence.dao.KgSubGroupMapper;

/**
 * autoGenerated
 * 
 * @date 2020年06月08日 11:50:55
 * @author Generator
 */
@Service("kgSubGroupService")
public class KgSubGroupServiceImpl implements KgSubGroupService {

	@Autowired
	KgSubGroupMapperAdapter kgSubGroupMapper;

	@Autowired
	KgEditSubGroupService kgEditSubGroupService;

	@Autowired
	KgEditSubGroupMapperAdapter kgEditSubGroupMapperAdapter;

	@Autowired
	KgEditDataMapperAdapter kgEditDataMapperAdapter;

	@Autowired
	KgEditDataService kgEditDataService;

	@Autowired
	KgDataLogMapperAdapter kgDataLogMapperAdapter;

	/**
	 * <p>
	 * New Info
	 * </p>
	 * 
	 * @param kgSubGroup
	 * @return
	 */
	@Transactional
	public Boolean add(LoginUser user, KgSubGroup kgSubGroup) {

		if (kgSubGroup.getId() == null || kgSubGroup.getId().equals(""))
			kgSubGroup.setId(UUIDUtil.get32UUID());

		if (kgSubGroup.getVersionId() == null || kgSubGroup.getVersionId().equals(""))
			kgSubGroup.setVersionId("1.0.0");

		if (user != null && user.getRoleId().contains(Constants.DEFAULT_ADMIN_ROLEID)) {

			return kgSubGroupMapper.insertSelective(kgSubGroup) > 0;
		} else {
			KgEditSubGroup data = new KgEditSubGroup(kgSubGroup);
			//data.setId(UUIDUtil.get32UUID());
			data.setId(kgSubGroup.getId());
			return kgEditSubGroupService.add(user, data);
		}
	}

	/**
	 * <p>
	 * Modify Info
	 * </p>
	 * 
	 * @param kgSubGroup
	 * @return
	 */
	@Transactional
	public Boolean modify(LoginUser user, KgSubGroup kgSubGroup) {
		if (user != null && user.getRoleId().contains(Constants.DEFAULT_ADMIN_ROLEID)) {
			return kgSubGroupMapper.updateByPrimaryKeySelective(kgSubGroup) > 0;
		} else {
			return kgEditSubGroupService.modify(user, new KgEditSubGroup(kgSubGroup));
		}
	}

	/**
	 * 操作正式表数据
	 * 
	 * @param id
	 * @param version
	 * @return
	 * @author:kxjl
	 * @date 2020年8月5日
	 */
	private Boolean deleteData(String id, String version) {
		if (id.contains(",")) {
			String[] ids = id.split(",");
			for (String tid : ids) {

				KgSubGroupKey key = new KgSubGroupKey();
				key.setId(tid);
				key.setVersionId(version);

				kgSubGroupMapper.deleteByPrimaryKey(key);

			}
			return true;
		} else {

			KgSubGroupKey key = new KgSubGroupKey();
			key.setId(id);
			key.setVersionId(version);

			return kgSubGroupMapper.deleteByPrimaryKey(key) > 0;

		}
	}

	/**
	 * <p>
	 * Delete
	 * </p>
	 * 
	 * @param id
	 * @return
	 */
	@Transactional
	public Boolean delete(LoginUser user, String id, String version) {

		if (user != null && user.getRoleId().contains(Constants.DEFAULT_ADMIN_ROLEID)) {

			return deleteData(id, version);
		} else {
			return kgEditSubGroupService.delete(user, id);
		}
	}

	/**
	 * <p>
	 * query info by id
	 * </p>
	 * 
	 * @param id
	 * @return
	 */
	@Transactional(readOnly = true)
	public KgSubGroup getOne(String id, String version) {

		KgSubGroupKey key = new KgSubGroupKey();
		key.setId(id);
		key.setVersionId(version);
		return kgSubGroupMapper.selectByPrimaryKey(key);
	}

	/**
	 * <p>
	 * query all info
	 * </p>
	 * 
	 * @return
	 */
	@Transactional(readOnly = true)
	public List<KgSubGroup> getAll() {
		KgSubGroupExample example = new KgSubGroupExample();
		return kgSubGroupMapper.selectByExample(example);
	}

	
	/**
	 * 增加查询列表改动标记
	 * @param user
	 * @param lst
	 * @author:kxjl
	 * @date 2020年8月6日
	 */
	private void addDiffFlag(LoginUser user, List<KgSubGroup> lst) {
		// 增加修改标记
		KgEditData equery = new KgEditData();
		equery.setEditUser(user.getUserId());
		equery.setAuditState("1");// 未提交
		List<KgEditData> edatas = kgEditDataMapperAdapter.selectList(equery);

		KgEditData equery2 = new KgEditData();
		equery2.setEditUser(user.getUserId());
		equery2.setAuditState("2");// 未提交
		List<KgEditData> edataAudits = kgEditDataMapperAdapter.selectList(equery2);

		JSONObject jedit = new JSONObject();

		for (KgSubGroup data : lst) {
			for (KgEditData eitem : edatas) {
				if (data.getId().equals(eitem.getEditOriDataId())||data.getId().equals(eitem.getEditDataId())) {

					jedit.put("editAction", eitem.getEditAction());
					jedit.put("auditState", "1");
					jedit.put("editDataId", eitem.getEditDataId());
					data.setMyEdit(jedit.toJSONString());
					
				//data.setMyEdit(eitem.getEditAction() + ":" + eitem.getEditDataId());
				}
			}

			for (KgEditData eitem : edataAudits) {
				if (data.getId().equals(eitem.getEditOriDataId())||data.getId().equals(eitem.getEditDataId())) 
				{
					jedit.put("editAction", eitem.getEditAction());
					jedit.put("auditState", "2");
					jedit.put("editDataId", eitem.getEditDataId());
					data.setMyEdit(jedit.toJSONString());
				}
					
				//	data.setMyEdit("4:" + eitem.getEditDataId());
			}

		}

	}

	/**
	 * 
	 * @param example
	 * @return
	 * @author:kxjl
	 * @date 2020年6月9日
	 */
	public Page<KgSubGroup> selectList(LoginUser user, KgSubGroup query, Pagination pageCondition) {
		com.github.pagehelper.Page pageinfo = PageUtil.getPage(pageCondition);

		query.setCurUser(user.getUserId());
		List<KgSubGroup> lst = kgSubGroupMapper.selectList(query);
		
		addDiffFlag(user,lst);

		Page<KgSubGroup> page = new Page<KgSubGroup>();
		page.setResults(lst);
		page.setPageNo(pageinfo.getPageNum());
		page.setPageSize(pageinfo.getPageSize());
		page.setTotalRecord((int) pageinfo.getTotal());

		return page;
	}

	@Transactional
	public WZResponseEntity<?> audit(LoginUser user, KgSubGroup kgSubGroup, KgEditData editData) {

		WZResponseEntity<?> rst = new WZResponseEntity<>();

		String auditRstId = "";// 当前审核合并后的数据id,也存到 对应的edit表中.
		if (editData.getAuditState().equals("5")) // 不通过
		{

		} else if (editData.getAuditState().equals("3") || editData.getAuditState().equals("4")) // 通过
		{

			KgSubGroup olddata = getOne(kgSubGroup.getId(), Constants.DEFULT_VERSION);

			// 多人修改,并且多个人全部为删除操作，则最后删除
			if (editData.getEditAction().contains(",")) {
				String[] actions = editData.getEditAction().split(",");
				boolean alldelete = true;
				for (String ac : actions) {
					if (!ac.equals("3")) {
						alldelete = false;
						break;
					}
				}
				if (alldelete) {
					deleteData(editData.getEditOriDataId(), Constants.DEFULT_VERSION);
				}

			}

			// 修改真实数据
			if (editData.getEditAction().equals("3"))// 单人删除
			{
				deleteData(editData.getEditOriDataId(), Constants.DEFULT_VERSION);
			} else if (editData.getEditAction().equals("1"))// 单人新增
			{
			
				kgSubGroupMapper.insertSelective(kgSubGroup);
			} else // 合并修改，只要有一个人不删除，均按修改操作
			{
				kgSubGroupMapper.updateByPrimaryKeySelective(kgSubGroup);
			}

			// 保存当前审核结果数据备份，包括删除的
			KgSubGroup auditRst = getOne(kgSubGroup.getId(), Constants.DEFULT_VERSION);
			if (auditRst != null) {

				KgEditSubGroup edata = new KgEditSubGroup(auditRst);
				auditRstId = UUIDUtil.get32UUID();
				edata.setId(auditRstId);
				kgEditSubGroupMapperAdapter.insertSelective(edata);

			} else {
				// 保存删除的快照
				KgEditSubGroup eolddata = new KgEditSubGroup(olddata);
				auditRstId = UUIDUtil.get32UUID();
				eolddata.setId(auditRstId);
				kgEditSubGroupMapperAdapter.insertSelective(eolddata);
			}

			// 保存快照数据id
			editData.setAuditRstId(auditRstId);

			
			String idold = "";
			if(olddata!=null)
			{
			// 保存编辑前数据备份-》edit表
			KgEditSubGroup eolddata = new KgEditSubGroup(olddata);
			 idold = UUIDUtil.get32UUID();
			eolddata.setId(idold);
			kgEditSubGroupMapperAdapter.insertSelective(eolddata);
			}

			// 记录数据修改日志
			KgDataLog dlog = new KgDataLog();
			dlog.setId(UUIDUtil.get32UUID());
			dlog.setAuditUser(user.getUserId());
			dlog.setDataId(kgSubGroup.getId());
			dlog.setDataType("1");
			dlog.setEditAction(editData.getEditAction());
			dlog.setEditUser(editData.getEditUser());
			dlog.setEditUserName(editData.getEditUserName());

			// 记录对应备份的数据id
			dlog.setEditDataPre(idold);
			dlog.setEditDataNext(auditRstId);

			kgDataLogMapperAdapter.insertSelective(dlog);

		}

		// 修改审核数据
		kgEditDataService.audit(user, editData);

		rst.setIsSuccess(true);

		return rst;
	}

}