package com.kxjl.admin.persistence.entity;

public class KgDataAuditDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_DATA_AUDIT_DETAIL.ID
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_DATA_AUDIT_DETAIL.DATA_AUDIT_ID
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    private String dataAuditId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_DATA_AUDIT_DETAIL.DATA_EDIT_ID
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    private String dataEditId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_DATA_AUDIT_DETAIL.ID
     *
     * @return the value of KG_DATA_AUDIT_DETAIL.ID
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_DATA_AUDIT_DETAIL.ID
     *
     * @param id the value for KG_DATA_AUDIT_DETAIL.ID
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_DATA_AUDIT_DETAIL.DATA_AUDIT_ID
     *
     * @return the value of KG_DATA_AUDIT_DETAIL.DATA_AUDIT_ID
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    public String getDataAuditId() {
        return dataAuditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_DATA_AUDIT_DETAIL.DATA_AUDIT_ID
     *
     * @param dataAuditId the value for KG_DATA_AUDIT_DETAIL.DATA_AUDIT_ID
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    public void setDataAuditId(String dataAuditId) {
        this.dataAuditId = dataAuditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_DATA_AUDIT_DETAIL.DATA_EDIT_ID
     *
     * @return the value of KG_DATA_AUDIT_DETAIL.DATA_EDIT_ID
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    public String getDataEditId() {
        return dataEditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_DATA_AUDIT_DETAIL.DATA_EDIT_ID
     *
     * @param dataEditId the value for KG_DATA_AUDIT_DETAIL.DATA_EDIT_ID
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    public void setDataEditId(String dataEditId) {
        this.dataEditId = dataEditId;
    }
}