package com.kxjl.admin.persistence.entity;

import java.util.Date;

public class KgDataLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_DATA_LOG.ID
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_DATA_LOG.DATA_ID
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    private String dataId;

    /**
     *
    '1:领域，2：目录，3概念，4属性，5关系，6实体,7实体关系'，
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    private String dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_DATA_LOG.EDIT_USER
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    private String editUser;
    
    private String editUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_DATA_LOG.EDIT_ACTION
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    private String editAction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_DATA_LOG.EDIT_DATE
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    private Date editDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_DATA_LOG.AUDIT_USER
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    private String auditUser;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column KG_DATA_LOG.EDIT_DATA_PRE
    *
    * @mbg.generated Mon Aug 03 13:27:33 CST 2020
    */
   private String editDataPre;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column KG_DATA_LOG.EDIT_DATA_NEXT
    *
    * @mbg.generated Mon Aug 03 13:27:33 CST 2020
    */
   private String editDataNext;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column KG_DATA_LOG.EDIT_DATA_PRE
    *
    * @return the value of KG_DATA_LOG.EDIT_DATA_PRE
    *
    * @mbg.generated Mon Aug 03 13:27:33 CST 2020
    */
   public String getEditDataPre() {
       return editDataPre;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column KG_DATA_LOG.EDIT_DATA_PRE
    *
    * @param editDataPre the value for KG_DATA_LOG.EDIT_DATA_PRE
    *
    * @mbg.generated Mon Aug 03 13:27:33 CST 2020
    */
   public void setEditDataPre(String editDataPre) {
       this.editDataPre = editDataPre;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column KG_DATA_LOG.EDIT_DATA_NEXT
    *
    * @return the value of KG_DATA_LOG.EDIT_DATA_NEXT
    *
    * @mbg.generated Mon Aug 03 13:27:33 CST 2020
    */
   public String getEditDataNext() {
       return editDataNext;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column KG_DATA_LOG.EDIT_DATA_NEXT
    *
    * @param editDataNext the value for KG_DATA_LOG.EDIT_DATA_NEXT
    *
    * @mbg.generated Mon Aug 03 13:27:33 CST 2020
    */
   public void setEditDataNext(String editDataNext) {
       this.editDataNext = editDataNext;
   }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_DATA_LOG.ID
     *
     * @return the value of KG_DATA_LOG.ID
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_DATA_LOG.ID
     *
     * @param id the value for KG_DATA_LOG.ID
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_DATA_LOG.DATA_ID
     *
     * @return the value of KG_DATA_LOG.DATA_ID
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_DATA_LOG.DATA_ID
     *
     * @param dataId the value for KG_DATA_LOG.DATA_ID
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     '1:领域，2：目录，3概念，4属性，5关系，6实体,7实体关系'，
     *
     * @return the value of KG_DATA_LOG.DATA_TYPE
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public String getDataType() {
        return dataType;
    }

    /**
    '1:领域，2：目录，3概念，4属性，5关系，6实体,7实体关系'，
     *
     * @param dataType the value for KG_DATA_LOG.DATA_TYPE
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_DATA_LOG.EDIT_USER
     *
     * @return the value of KG_DATA_LOG.EDIT_USER
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public String getEditUser() {
        return editUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_DATA_LOG.EDIT_USER
     *
     * @param editUser the value for KG_DATA_LOG.EDIT_USER
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public void setEditUser(String editUser) {
        this.editUser = editUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_DATA_LOG.EDIT_ACTION
     *
     * @return the value of KG_DATA_LOG.EDIT_ACTION
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public String getEditAction() {
        return editAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_DATA_LOG.EDIT_ACTION
     *
     * @param editAction the value for KG_DATA_LOG.EDIT_ACTION
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public void setEditAction(String editAction) {
        this.editAction = editAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_DATA_LOG.EDIT_DATE
     *
     * @return the value of KG_DATA_LOG.EDIT_DATE
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_DATA_LOG.EDIT_DATE
     *
     * @param editDate the value for KG_DATA_LOG.EDIT_DATE
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_DATA_LOG.AUDIT_USER
     *
     * @return the value of KG_DATA_LOG.AUDIT_USER
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public String getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_DATA_LOG.AUDIT_USER
     *
     * @param auditUser the value for KG_DATA_LOG.AUDIT_USER
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    public void setAuditUser(String auditUser) {
        this.auditUser = auditUser;
    }

	public String getEditUserName() {
		return editUserName;
	}

	public void setEditUserName(String editUserName) {
		this.editUserName = editUserName;
	}
}