package com.kxjl.admin.persistence.entity;

import java.util.Date;

import com.kxjl.admin.util.Constants;
import com.kxjl.admin.util.CopyUtil;

public class KgEditSubGroup extends KgSubGroup {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column KG_EDIT_SUB_GROUP.ORI_ID
	 *
	 * @mbg.generated Mon Aug 03 13:27:33 CST 2020
	 */
	private String oriId;

	public String getOriId() {
		return oriId;
	}

	public void setOriId(String oriId) {
		this.oriId = oriId;
	}

	public KgEditSubGroup(){
		
	}
	
	public KgEditSubGroup(KgSubGroup group) {
	
		
		CopyUtil.fatherToChild(group,this);
		this.setOriId(group.getId());
		this.setVersionId(Constants.DEFULT_VERSION);

	}

}