package com.kxjl.admin.persistence.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class KgEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public KgEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVersionIdIsNull() {
            addCriterion("VERSION_ID is null");
            return (Criteria) this;
        }

        public Criteria andVersionIdIsNotNull() {
            addCriterion("VERSION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andVersionIdEqualTo(String value) {
            addCriterion("VERSION_ID =", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotEqualTo(String value) {
            addCriterion("VERSION_ID <>", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdGreaterThan(String value) {
            addCriterion("VERSION_ID >", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdGreaterThanOrEqualTo(String value) {
            addCriterion("VERSION_ID >=", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdLessThan(String value) {
            addCriterion("VERSION_ID <", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdLessThanOrEqualTo(String value) {
            addCriterion("VERSION_ID <=", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdLike(String value) {
            addCriterion("VERSION_ID like", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotLike(String value) {
            addCriterion("VERSION_ID not like", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdIn(List<String> values) {
            addCriterion("VERSION_ID in", values, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotIn(List<String> values) {
            addCriterion("VERSION_ID not in", values, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdBetween(String value1, String value2) {
            addCriterion("VERSION_ID between", value1, value2, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotBetween(String value1, String value2) {
            addCriterion("VERSION_ID not between", value1, value2, "versionId");
            return (Criteria) this;
        }

        public Criteria andClsIdIsNull() {
            addCriterion("CLS_ID is null");
            return (Criteria) this;
        }

        public Criteria andClsIdIsNotNull() {
            addCriterion("CLS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andClsIdEqualTo(String value) {
            addCriterion("CLS_ID =", value, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsIdNotEqualTo(String value) {
            addCriterion("CLS_ID <>", value, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsIdGreaterThan(String value) {
            addCriterion("CLS_ID >", value, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsIdGreaterThanOrEqualTo(String value) {
            addCriterion("CLS_ID >=", value, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsIdLessThan(String value) {
            addCriterion("CLS_ID <", value, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsIdLessThanOrEqualTo(String value) {
            addCriterion("CLS_ID <=", value, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsIdLike(String value) {
            addCriterion("CLS_ID like", value, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsIdNotLike(String value) {
            addCriterion("CLS_ID not like", value, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsIdIn(List<String> values) {
            addCriterion("CLS_ID in", values, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsIdNotIn(List<String> values) {
            addCriterion("CLS_ID not in", values, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsIdBetween(String value1, String value2) {
            addCriterion("CLS_ID between", value1, value2, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsIdNotBetween(String value1, String value2) {
            addCriterion("CLS_ID not between", value1, value2, "clsId");
            return (Criteria) this;
        }

        public Criteria andClsNameIsNull() {
            addCriterion("CLS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andClsNameIsNotNull() {
            addCriterion("CLS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andClsNameEqualTo(String value) {
            addCriterion("CLS_NAME =", value, "clsName");
            return (Criteria) this;
        }

        public Criteria andClsNameNotEqualTo(String value) {
            addCriterion("CLS_NAME <>", value, "clsName");
            return (Criteria) this;
        }

        public Criteria andClsNameGreaterThan(String value) {
            addCriterion("CLS_NAME >", value, "clsName");
            return (Criteria) this;
        }

        public Criteria andClsNameGreaterThanOrEqualTo(String value) {
            addCriterion("CLS_NAME >=", value, "clsName");
            return (Criteria) this;
        }

        public Criteria andClsNameLessThan(String value) {
            addCriterion("CLS_NAME <", value, "clsName");
            return (Criteria) this;
        }

        public Criteria andClsNameLessThanOrEqualTo(String value) {
            addCriterion("CLS_NAME <=", value, "clsName");
            return (Criteria) this;
        }

        public Criteria andClsNameLike(String value) {
            addCriterion("CLS_NAME like", value, "clsName");
            return (Criteria) this;
        }

        public Criteria andClsNameNotLike(String value) {
            addCriterion("CLS_NAME not like", value, "clsName");
            return (Criteria) this;
        }

        public Criteria andClsNameIn(List<String> values) {
            addCriterion("CLS_NAME in", values, "clsName");
            return (Criteria) this;
        }

        public Criteria andClsNameNotIn(List<String> values) {
            addCriterion("CLS_NAME not in", values, "clsName");
            return (Criteria) this;
        }

        public Criteria andClsNameBetween(String value1, String value2) {
            addCriterion("CLS_NAME between", value1, value2, "clsName");
            return (Criteria) this;
        }

        public Criteria andClsNameNotBetween(String value1, String value2) {
            addCriterion("CLS_NAME not between", value1, value2, "clsName");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andFullNameIsNull() {
            addCriterion("FULL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFullNameIsNotNull() {
            addCriterion("FULL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFullNameEqualTo(String value) {
            addCriterion("FULL_NAME =", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotEqualTo(String value) {
            addCriterion("FULL_NAME <>", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameGreaterThan(String value) {
            addCriterion("FULL_NAME >", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameGreaterThanOrEqualTo(String value) {
            addCriterion("FULL_NAME >=", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLessThan(String value) {
            addCriterion("FULL_NAME <", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLessThanOrEqualTo(String value) {
            addCriterion("FULL_NAME <=", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLike(String value) {
            addCriterion("FULL_NAME like", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotLike(String value) {
            addCriterion("FULL_NAME not like", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameIn(List<String> values) {
            addCriterion("FULL_NAME in", values, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotIn(List<String> values) {
            addCriterion("FULL_NAME not in", values, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameBetween(String value1, String value2) {
            addCriterion("FULL_NAME between", value1, value2, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotBetween(String value1, String value2) {
            addCriterion("FULL_NAME not between", value1, value2, "fullName");
            return (Criteria) this;
        }

        public Criteria andSubKgIdIsNull() {
            addCriterion("SUB_KG_ID is null");
            return (Criteria) this;
        }

        public Criteria andSubKgIdIsNotNull() {
            addCriterion("SUB_KG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSubKgIdEqualTo(String value) {
            addCriterion("SUB_KG_ID =", value, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgIdNotEqualTo(String value) {
            addCriterion("SUB_KG_ID <>", value, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgIdGreaterThan(String value) {
            addCriterion("SUB_KG_ID >", value, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgIdGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_KG_ID >=", value, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgIdLessThan(String value) {
            addCriterion("SUB_KG_ID <", value, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgIdLessThanOrEqualTo(String value) {
            addCriterion("SUB_KG_ID <=", value, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgIdLike(String value) {
            addCriterion("SUB_KG_ID like", value, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgIdNotLike(String value) {
            addCriterion("SUB_KG_ID not like", value, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgIdIn(List<String> values) {
            addCriterion("SUB_KG_ID in", values, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgIdNotIn(List<String> values) {
            addCriterion("SUB_KG_ID not in", values, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgIdBetween(String value1, String value2) {
            addCriterion("SUB_KG_ID between", value1, value2, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgIdNotBetween(String value1, String value2) {
            addCriterion("SUB_KG_ID not between", value1, value2, "subKgId");
            return (Criteria) this;
        }

        public Criteria andSubKgNameIsNull() {
            addCriterion("SUB_KG_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSubKgNameIsNotNull() {
            addCriterion("SUB_KG_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSubKgNameEqualTo(String value) {
            addCriterion("SUB_KG_NAME =", value, "subKgName");
            return (Criteria) this;
        }

        public Criteria andSubKgNameNotEqualTo(String value) {
            addCriterion("SUB_KG_NAME <>", value, "subKgName");
            return (Criteria) this;
        }

        public Criteria andSubKgNameGreaterThan(String value) {
            addCriterion("SUB_KG_NAME >", value, "subKgName");
            return (Criteria) this;
        }

        public Criteria andSubKgNameGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_KG_NAME >=", value, "subKgName");
            return (Criteria) this;
        }

        public Criteria andSubKgNameLessThan(String value) {
            addCriterion("SUB_KG_NAME <", value, "subKgName");
            return (Criteria) this;
        }

        public Criteria andSubKgNameLessThanOrEqualTo(String value) {
            addCriterion("SUB_KG_NAME <=", value, "subKgName");
            return (Criteria) this;
        }

        public Criteria andSubKgNameLike(String value) {
            addCriterion("SUB_KG_NAME like", value, "subKgName");
            return (Criteria) this;
        }

        public Criteria andSubKgNameNotLike(String value) {
            addCriterion("SUB_KG_NAME not like", value, "subKgName");
            return (Criteria) this;
        }

        public Criteria andSubKgNameIn(List<String> values) {
            addCriterion("SUB_KG_NAME in", values, "subKgName");
            return (Criteria) this;
        }

        public Criteria andSubKgNameNotIn(List<String> values) {
            addCriterion("SUB_KG_NAME not in", values, "subKgName");
            return (Criteria) this;
        }

        public Criteria andSubKgNameBetween(String value1, String value2) {
            addCriterion("SUB_KG_NAME between", value1, value2, "subKgName");
            return (Criteria) this;
        }

        public Criteria andSubKgNameNotBetween(String value1, String value2) {
            addCriterion("SUB_KG_NAME not between", value1, value2, "subKgName");
            return (Criteria) this;
        }

        public Criteria andPropertiesIsNull() {
            addCriterion("PROPERTIES is null");
            return (Criteria) this;
        }

        public Criteria andPropertiesIsNotNull() {
            addCriterion("PROPERTIES is not null");
            return (Criteria) this;
        }

        public Criteria andPropertiesEqualTo(String value) {
            addCriterion("PROPERTIES =", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotEqualTo(String value) {
            addCriterion("PROPERTIES <>", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesGreaterThan(String value) {
            addCriterion("PROPERTIES >", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTIES >=", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLessThan(String value) {
            addCriterion("PROPERTIES <", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLessThanOrEqualTo(String value) {
            addCriterion("PROPERTIES <=", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLike(String value) {
            addCriterion("PROPERTIES like", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotLike(String value) {
            addCriterion("PROPERTIES not like", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesIn(List<String> values) {
            addCriterion("PROPERTIES in", values, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotIn(List<String> values) {
            addCriterion("PROPERTIES not in", values, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesBetween(String value1, String value2) {
            addCriterion("PROPERTIES between", value1, value2, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotBetween(String value1, String value2) {
            addCriterion("PROPERTIES not between", value1, value2, "properties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesIsNull() {
            addCriterion("EXT_PROPERTIES is null");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesIsNotNull() {
            addCriterion("EXT_PROPERTIES is not null");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesEqualTo(String value) {
            addCriterion("EXT_PROPERTIES =", value, "extProperties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesNotEqualTo(String value) {
            addCriterion("EXT_PROPERTIES <>", value, "extProperties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesGreaterThan(String value) {
            addCriterion("EXT_PROPERTIES >", value, "extProperties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesGreaterThanOrEqualTo(String value) {
            addCriterion("EXT_PROPERTIES >=", value, "extProperties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesLessThan(String value) {
            addCriterion("EXT_PROPERTIES <", value, "extProperties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesLessThanOrEqualTo(String value) {
            addCriterion("EXT_PROPERTIES <=", value, "extProperties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesLike(String value) {
            addCriterion("EXT_PROPERTIES like", value, "extProperties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesNotLike(String value) {
            addCriterion("EXT_PROPERTIES not like", value, "extProperties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesIn(List<String> values) {
            addCriterion("EXT_PROPERTIES in", values, "extProperties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesNotIn(List<String> values) {
            addCriterion("EXT_PROPERTIES not in", values, "extProperties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesBetween(String value1, String value2) {
            addCriterion("EXT_PROPERTIES between", value1, value2, "extProperties");
            return (Criteria) this;
        }

        public Criteria andExtPropertiesNotBetween(String value1, String value2) {
            addCriterion("EXT_PROPERTIES not between", value1, value2, "extProperties");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("TAGS is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("TAGS is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("TAGS =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("TAGS <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("TAGS >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("TAGS >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("TAGS <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("TAGS <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("TAGS like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("TAGS not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("TAGS in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("TAGS not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("TAGS between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("TAGS not between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andDirIdIsNull() {
            addCriterion("DIR_ID is null");
            return (Criteria) this;
        }

        public Criteria andDirIdIsNotNull() {
            addCriterion("DIR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDirIdEqualTo(String value) {
            addCriterion("DIR_ID =", value, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirIdNotEqualTo(String value) {
            addCriterion("DIR_ID <>", value, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirIdGreaterThan(String value) {
            addCriterion("DIR_ID >", value, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirIdGreaterThanOrEqualTo(String value) {
            addCriterion("DIR_ID >=", value, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirIdLessThan(String value) {
            addCriterion("DIR_ID <", value, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirIdLessThanOrEqualTo(String value) {
            addCriterion("DIR_ID <=", value, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirIdLike(String value) {
            addCriterion("DIR_ID like", value, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirIdNotLike(String value) {
            addCriterion("DIR_ID not like", value, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirIdIn(List<String> values) {
            addCriterion("DIR_ID in", values, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirIdNotIn(List<String> values) {
            addCriterion("DIR_ID not in", values, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirIdBetween(String value1, String value2) {
            addCriterion("DIR_ID between", value1, value2, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirIdNotBetween(String value1, String value2) {
            addCriterion("DIR_ID not between", value1, value2, "dirId");
            return (Criteria) this;
        }

        public Criteria andDirCodeIsNull() {
            addCriterion("DIR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andDirCodeIsNotNull() {
            addCriterion("DIR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andDirCodeEqualTo(String value) {
            addCriterion("DIR_CODE =", value, "dirCode");
            return (Criteria) this;
        }

        public Criteria andDirCodeNotEqualTo(String value) {
            addCriterion("DIR_CODE <>", value, "dirCode");
            return (Criteria) this;
        }

        public Criteria andDirCodeGreaterThan(String value) {
            addCriterion("DIR_CODE >", value, "dirCode");
            return (Criteria) this;
        }

        public Criteria andDirCodeGreaterThanOrEqualTo(String value) {
            addCriterion("DIR_CODE >=", value, "dirCode");
            return (Criteria) this;
        }

        public Criteria andDirCodeLessThan(String value) {
            addCriterion("DIR_CODE <", value, "dirCode");
            return (Criteria) this;
        }

        public Criteria andDirCodeLessThanOrEqualTo(String value) {
            addCriterion("DIR_CODE <=", value, "dirCode");
            return (Criteria) this;
        }

        public Criteria andDirCodeLike(String value) {
            addCriterion("DIR_CODE like", value, "dirCode");
            return (Criteria) this;
        }

        public Criteria andDirCodeNotLike(String value) {
            addCriterion("DIR_CODE not like", value, "dirCode");
            return (Criteria) this;
        }

        public Criteria andDirCodeIn(List<String> values) {
            addCriterion("DIR_CODE in", values, "dirCode");
            return (Criteria) this;
        }

        public Criteria andDirCodeNotIn(List<String> values) {
            addCriterion("DIR_CODE not in", values, "dirCode");
            return (Criteria) this;
        }

        public Criteria andDirCodeBetween(String value1, String value2) {
            addCriterion("DIR_CODE between", value1, value2, "dirCode");
            return (Criteria) this;
        }

        public Criteria andDirCodeNotBetween(String value1, String value2) {
            addCriterion("DIR_CODE not between", value1, value2, "dirCode");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("ENABLED is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("ENABLED is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(String value) {
            addCriterion("ENABLED =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(String value) {
            addCriterion("ENABLED <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(String value) {
            addCriterion("ENABLED >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(String value) {
            addCriterion("ENABLED >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(String value) {
            addCriterion("ENABLED <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(String value) {
            addCriterion("ENABLED <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLike(String value) {
            addCriterion("ENABLED like", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotLike(String value) {
            addCriterion("ENABLED not like", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<String> values) {
            addCriterion("ENABLED in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<String> values) {
            addCriterion("ENABLED not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(String value1, String value2) {
            addCriterion("ENABLED between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(String value1, String value2) {
            addCriterion("ENABLED not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("DELETED is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(String value) {
            addCriterion("DELETED =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(String value) {
            addCriterion("DELETED <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(String value) {
            addCriterion("DELETED >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("DELETED >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(String value) {
            addCriterion("DELETED <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(String value) {
            addCriterion("DELETED <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLike(String value) {
            addCriterion("DELETED like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotLike(String value) {
            addCriterion("DELETED not like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<String> values) {
            addCriterion("DELETED in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<String> values) {
            addCriterion("DELETED not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(String value1, String value2) {
            addCriterion("DELETED between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(String value1, String value2) {
            addCriterion("DELETED not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNull() {
            addCriterion("CREATED_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNotNull() {
            addCriterion("CREATED_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserEqualTo(String value) {
            addCriterion("CREATED_USER =", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotEqualTo(String value) {
            addCriterion("CREATED_USER <>", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThan(String value) {
            addCriterion("CREATED_USER >", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_USER >=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThan(String value) {
            addCriterion("CREATED_USER <", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThanOrEqualTo(String value) {
            addCriterion("CREATED_USER <=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLike(String value) {
            addCriterion("CREATED_USER like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotLike(String value) {
            addCriterion("CREATED_USER not like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIn(List<String> values) {
            addCriterion("CREATED_USER in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotIn(List<String> values) {
            addCriterion("CREATED_USER not in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserBetween(String value1, String value2) {
            addCriterion("CREATED_USER between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotBetween(String value1, String value2) {
            addCriterion("CREATED_USER not between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CREATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CREATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CREATED_TIME =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CREATED_TIME <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CREATED_TIME >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CREATED_TIME <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CREATED_TIME in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CREATED_TIME not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIsNull() {
            addCriterion("UPDATED_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIsNotNull() {
            addCriterion("UPDATED_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserEqualTo(String value) {
            addCriterion("UPDATED_USER =", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserNotEqualTo(String value) {
            addCriterion("UPDATED_USER <>", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserGreaterThan(String value) {
            addCriterion("UPDATED_USER >", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATED_USER >=", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserLessThan(String value) {
            addCriterion("UPDATED_USER <", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATED_USER <=", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserLike(String value) {
            addCriterion("UPDATED_USER like", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserNotLike(String value) {
            addCriterion("UPDATED_USER not like", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIn(List<String> values) {
            addCriterion("UPDATED_USER in", values, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserNotIn(List<String> values) {
            addCriterion("UPDATED_USER not in", values, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserBetween(String value1, String value2) {
            addCriterion("UPDATED_USER between", value1, value2, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserNotBetween(String value1, String value2) {
            addCriterion("UPDATED_USER not between", value1, value2, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("UPDATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("UPDATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterion("UPDATED_TIME =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterion("UPDATED_TIME <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterion("UPDATED_TIME >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED_TIME >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterion("UPDATED_TIME <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED_TIME <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterion("UPDATED_TIME in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterion("UPDATED_TIME not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATED_TIME between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED_TIME not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KG_ENTITY
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 22 09:29:11 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}