package com.kxjl.admin.persistence.entity;

import java.math.BigDecimal;
import java.util.Date;

public class KgObjectProperty extends KgObjectPropertyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.CLS_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String clsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.CLS_NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String clsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.RELATION_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.RELATION_NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String relationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.PROP_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String propId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.PROP_NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String propName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.TYPE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.DATA_TYPE_RULE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String dataTypeRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.SORT
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private BigDecimal sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.WEIGHT
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.ENABLED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.DELETED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String updatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_PROPERTY.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.CLS_ID
     *
     * @return the value of KG_OBJECT_PROPERTY.CLS_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getClsId() {
        return clsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.CLS_ID
     *
     * @param clsId the value for KG_OBJECT_PROPERTY.CLS_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setClsId(String clsId) {
        this.clsId = clsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.CLS_NAME
     *
     * @return the value of KG_OBJECT_PROPERTY.CLS_NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getClsName() {
        return clsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.CLS_NAME
     *
     * @param clsName the value for KG_OBJECT_PROPERTY.CLS_NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setClsName(String clsName) {
        this.clsName = clsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.RELATION_ID
     *
     * @return the value of KG_OBJECT_PROPERTY.RELATION_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.RELATION_ID
     *
     * @param relationId the value for KG_OBJECT_PROPERTY.RELATION_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setRelationId(String relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.RELATION_NAME
     *
     * @return the value of KG_OBJECT_PROPERTY.RELATION_NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getRelationName() {
        return relationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.RELATION_NAME
     *
     * @param relationName the value for KG_OBJECT_PROPERTY.RELATION_NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setRelationName(String relationName) {
        this.relationName = relationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.PROP_ID
     *
     * @return the value of KG_OBJECT_PROPERTY.PROP_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getPropId() {
        return propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.PROP_ID
     *
     * @param propId the value for KG_OBJECT_PROPERTY.PROP_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setPropId(String propId) {
        this.propId = propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.PROP_NAME
     *
     * @return the value of KG_OBJECT_PROPERTY.PROP_NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getPropName() {
        return propName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.PROP_NAME
     *
     * @param propName the value for KG_OBJECT_PROPERTY.PROP_NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setPropName(String propName) {
        this.propName = propName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.TYPE
     *
     * @return the value of KG_OBJECT_PROPERTY.TYPE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.TYPE
     *
     * @param type the value for KG_OBJECT_PROPERTY.TYPE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.DATA_TYPE_RULE
     *
     * @return the value of KG_OBJECT_PROPERTY.DATA_TYPE_RULE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getDataTypeRule() {
        return dataTypeRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.DATA_TYPE_RULE
     *
     * @param dataTypeRule the value for KG_OBJECT_PROPERTY.DATA_TYPE_RULE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setDataTypeRule(String dataTypeRule) {
        this.dataTypeRule = dataTypeRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.SORT
     *
     * @return the value of KG_OBJECT_PROPERTY.SORT
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public BigDecimal getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.SORT
     *
     * @param sort the value for KG_OBJECT_PROPERTY.SORT
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setSort(BigDecimal sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.WEIGHT
     *
     * @return the value of KG_OBJECT_PROPERTY.WEIGHT
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.WEIGHT
     *
     * @param weight the value for KG_OBJECT_PROPERTY.WEIGHT
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.ENABLED
     *
     * @return the value of KG_OBJECT_PROPERTY.ENABLED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.ENABLED
     *
     * @param enabled the value for KG_OBJECT_PROPERTY.ENABLED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.DELETED
     *
     * @return the value of KG_OBJECT_PROPERTY.DELETED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.DELETED
     *
     * @param deleted the value for KG_OBJECT_PROPERTY.DELETED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.CREATED_USER
     *
     * @return the value of KG_OBJECT_PROPERTY.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.CREATED_USER
     *
     * @param createdUser the value for KG_OBJECT_PROPERTY.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.CREATED_TIME
     *
     * @return the value of KG_OBJECT_PROPERTY.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.CREATED_TIME
     *
     * @param createdTime the value for KG_OBJECT_PROPERTY.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.UPDATED_USER
     *
     * @return the value of KG_OBJECT_PROPERTY.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.UPDATED_USER
     *
     * @param updatedUser the value for KG_OBJECT_PROPERTY.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_PROPERTY.UPDATED_TIME
     *
     * @return the value of KG_OBJECT_PROPERTY.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_PROPERTY.UPDATED_TIME
     *
     * @param updatedTime the value for KG_OBJECT_PROPERTY.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}