package com.kxjl.admin.persistence.entity;

public class KgObjectRelationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_RELATION.ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_OBJECT_RELATION.VERSION_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String versionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_RELATION.ID
     *
     * @return the value of KG_OBJECT_RELATION.ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_RELATION.ID
     *
     * @param id the value for KG_OBJECT_RELATION.ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_OBJECT_RELATION.VERSION_ID
     *
     * @return the value of KG_OBJECT_RELATION.VERSION_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_OBJECT_RELATION.VERSION_ID
     *
     * @param versionId the value for KG_OBJECT_RELATION.VERSION_ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId;
    }
}