package com.kxjl.admin.persistence.entity;

import java.util.Date;

public class KgPropertyDatatype extends KgPropertyDatatypeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.NAME
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.CODE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.REGULAR
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String regular;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.MIN_LENGTH
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String minLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.MAX_LENGTH
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String maxLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.LENGTH
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.ENUM_TYPE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String enumType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.MAX_VALUE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String maxValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.MIN_VALUE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String minValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.ENABLE_EMPTY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String enableEmpty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.SAVE_TYPE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String saveType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.ERROR_TIP
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String errorTip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.EXAMPLE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String example;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.REMARK
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.CREATED_USER
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.CREATED_TIME
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.UPDATED_USER
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private String updatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_PROPERTY_DATATYPE.UPDATED_TIME
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.NAME
     *
     * @return the value of KG_PROPERTY_DATATYPE.NAME
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.NAME
     *
     * @param name the value for KG_PROPERTY_DATATYPE.NAME
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.CODE
     *
     * @return the value of KG_PROPERTY_DATATYPE.CODE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.CODE
     *
     * @param code the value for KG_PROPERTY_DATATYPE.CODE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.REGULAR
     *
     * @return the value of KG_PROPERTY_DATATYPE.REGULAR
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getRegular() {
        return regular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.REGULAR
     *
     * @param regular the value for KG_PROPERTY_DATATYPE.REGULAR
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setRegular(String regular) {
        this.regular = regular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.MIN_LENGTH
     *
     * @return the value of KG_PROPERTY_DATATYPE.MIN_LENGTH
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getMinLength() {
        return minLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.MIN_LENGTH
     *
     * @param minLength the value for KG_PROPERTY_DATATYPE.MIN_LENGTH
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setMinLength(String minLength) {
        this.minLength = minLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.MAX_LENGTH
     *
     * @return the value of KG_PROPERTY_DATATYPE.MAX_LENGTH
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getMaxLength() {
        return maxLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.MAX_LENGTH
     *
     * @param maxLength the value for KG_PROPERTY_DATATYPE.MAX_LENGTH
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setMaxLength(String maxLength) {
        this.maxLength = maxLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.LENGTH
     *
     * @return the value of KG_PROPERTY_DATATYPE.LENGTH
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.LENGTH
     *
     * @param length the value for KG_PROPERTY_DATATYPE.LENGTH
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setLength(String length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.ENUM_TYPE
     *
     * @return the value of KG_PROPERTY_DATATYPE.ENUM_TYPE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getEnumType() {
        return enumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.ENUM_TYPE
     *
     * @param enumType the value for KG_PROPERTY_DATATYPE.ENUM_TYPE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setEnumType(String enumType) {
        this.enumType = enumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.MAX_VALUE
     *
     * @return the value of KG_PROPERTY_DATATYPE.MAX_VALUE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.MAX_VALUE
     *
     * @param maxValue the value for KG_PROPERTY_DATATYPE.MAX_VALUE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setMaxValue(String maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.MIN_VALUE
     *
     * @return the value of KG_PROPERTY_DATATYPE.MIN_VALUE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.MIN_VALUE
     *
     * @param minValue the value for KG_PROPERTY_DATATYPE.MIN_VALUE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setMinValue(String minValue) {
        this.minValue = minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.ENABLE_EMPTY
     *
     * @return the value of KG_PROPERTY_DATATYPE.ENABLE_EMPTY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getEnableEmpty() {
        return enableEmpty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.ENABLE_EMPTY
     *
     * @param enableEmpty the value for KG_PROPERTY_DATATYPE.ENABLE_EMPTY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setEnableEmpty(String enableEmpty) {
        this.enableEmpty = enableEmpty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.SAVE_TYPE
     *
     * @return the value of KG_PROPERTY_DATATYPE.SAVE_TYPE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getSaveType() {
        return saveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.SAVE_TYPE
     *
     * @param saveType the value for KG_PROPERTY_DATATYPE.SAVE_TYPE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setSaveType(String saveType) {
        this.saveType = saveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.ERROR_TIP
     *
     * @return the value of KG_PROPERTY_DATATYPE.ERROR_TIP
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getErrorTip() {
        return errorTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.ERROR_TIP
     *
     * @param errorTip the value for KG_PROPERTY_DATATYPE.ERROR_TIP
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setErrorTip(String errorTip) {
        this.errorTip = errorTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.EXAMPLE
     *
     * @return the value of KG_PROPERTY_DATATYPE.EXAMPLE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getExample() {
        return example;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.EXAMPLE
     *
     * @param example the value for KG_PROPERTY_DATATYPE.EXAMPLE
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setExample(String example) {
        this.example = example;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.REMARK
     *
     * @return the value of KG_PROPERTY_DATATYPE.REMARK
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.REMARK
     *
     * @param remark the value for KG_PROPERTY_DATATYPE.REMARK
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.CREATED_USER
     *
     * @return the value of KG_PROPERTY_DATATYPE.CREATED_USER
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.CREATED_USER
     *
     * @param createdUser the value for KG_PROPERTY_DATATYPE.CREATED_USER
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.CREATED_TIME
     *
     * @return the value of KG_PROPERTY_DATATYPE.CREATED_TIME
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.CREATED_TIME
     *
     * @param createdTime the value for KG_PROPERTY_DATATYPE.CREATED_TIME
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.UPDATED_USER
     *
     * @return the value of KG_PROPERTY_DATATYPE.UPDATED_USER
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.UPDATED_USER
     *
     * @param updatedUser the value for KG_PROPERTY_DATATYPE.UPDATED_USER
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_PROPERTY_DATATYPE.UPDATED_TIME
     *
     * @return the value of KG_PROPERTY_DATATYPE.UPDATED_TIME
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_PROPERTY_DATATYPE.UPDATED_TIME
     *
     * @param updatedTime the value for KG_PROPERTY_DATATYPE.UPDATED_TIME
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}