package com.kxjl.admin.persistence.entity;

import java.util.Date;

public class KgRelation extends KgRelationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.EQUIVALENCE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String equivalence;
    
    private String equivalenceNames;
    /**
     * 数据审核中当前数据来源，"1:正式数据,2:编辑中的数据"
     */
    private String dataFromType;//数据审核中当前数据来源，"1:正式数据,2:编辑中的数据"

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.REVERSE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String reverse;
    
    private String reverseNames;
    
    private String attrs;
    
    private String attrNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.TRANSITIVITY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String transitivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.SYMMETRY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String symmetry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.REMARK
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.ENABLED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.DELETED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String updatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_RELATION.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private Date updatedTime;
    
    
    private String myEdit;//自己是否有修改过
    
    private String curUser;//当前查询用户

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.NAME
     *
     * @return the value of KG_RELATION.NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.NAME
     *
     * @param name the value for KG_RELATION.NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.EQUIVALENCE
     *
     * @return the value of KG_RELATION.EQUIVALENCE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getEquivalence() {
        return equivalence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.EQUIVALENCE
     *
     * @param equivalence the value for KG_RELATION.EQUIVALENCE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setEquivalence(String equivalence) {
        this.equivalence = equivalence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.REVERSE
     *
     * @return the value of KG_RELATION.REVERSE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getReverse() {
        return reverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.REVERSE
     *
     * @param reverse the value for KG_RELATION.REVERSE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setReverse(String reverse) {
        this.reverse = reverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.TRANSITIVITY
     *
     * @return the value of KG_RELATION.TRANSITIVITY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getTransitivity() {
        return transitivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.TRANSITIVITY
     *
     * @param transitivity the value for KG_RELATION.TRANSITIVITY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setTransitivity(String transitivity) {
        this.transitivity = transitivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.SYMMETRY
     *
     * @return the value of KG_RELATION.SYMMETRY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getSymmetry() {
        return symmetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.SYMMETRY
     *
     * @param symmetry the value for KG_RELATION.SYMMETRY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setSymmetry(String symmetry) {
        this.symmetry = symmetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.REMARK
     *
     * @return the value of KG_RELATION.REMARK
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.REMARK
     *
     * @param remark the value for KG_RELATION.REMARK
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.ENABLED
     *
     * @return the value of KG_RELATION.ENABLED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.ENABLED
     *
     * @param enabled the value for KG_RELATION.ENABLED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.DELETED
     *
     * @return the value of KG_RELATION.DELETED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.DELETED
     *
     * @param deleted the value for KG_RELATION.DELETED
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.CREATED_USER
     *
     * @return the value of KG_RELATION.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.CREATED_USER
     *
     * @param createdUser the value for KG_RELATION.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.CREATED_TIME
     *
     * @return the value of KG_RELATION.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.CREATED_TIME
     *
     * @param createdTime the value for KG_RELATION.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.UPDATED_USER
     *
     * @return the value of KG_RELATION.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.UPDATED_USER
     *
     * @param updatedUser the value for KG_RELATION.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_RELATION.UPDATED_TIME
     *
     * @return the value of KG_RELATION.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_RELATION.UPDATED_TIME
     *
     * @param updatedTime the value for KG_RELATION.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

	public String getAttrs() {
		return attrs;
	}

	public void setAttrs(String attrs) {
		this.attrs = attrs;
	}

	public String getAttrNames() {
		return attrNames;
	}

	public void setAttrNames(String attrNames) {
		this.attrNames = attrNames;
	}

	public String getEquivalenceNames() {
		return equivalenceNames;
	}

	public void setEquivalenceNames(String equivalenceNames) {
		this.equivalenceNames = equivalenceNames;
	}

	public String getReverseNames() {
		return reverseNames;
	}

	public void setReverseNames(String reverseNames) {
		this.reverseNames = reverseNames;
	}

	public String getMyEdit() {
		return myEdit;
	}

	public void setMyEdit(String myEdit) {
		this.myEdit = myEdit;
	}

	public String getCurUser() {
		return curUser;
	}

	public void setCurUser(String curUser) {
		this.curUser = curUser;
	}
	/**
	 * 数据审核中当前数据来源，"1:正式数据,2:编辑中的数据"
	 * @return
	 * @author:kxjl
	 * @date 2020年8月20日
	 */
	public String getDataFromType() {
		return dataFromType;
	}

	/**
	 * 数据审核中当前数据来源，"1:正式数据,2:编辑中的数据"
	 * @param dataFromType
	 * @author:kxjl
	 * @date 2020年8月20日
	 */
	public void setDataFromType(String dataFromType) {
		this.dataFromType = dataFromType;
	}
	
}