package com.kxjl.admin.persistence.entity;

import java.util.Date;

public class KgSubGroup extends KgSubGroupKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_SUB_GROUP.NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_SUB_GROUP.REMARK
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_SUB_GROUP.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_SUB_GROUP.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_SUB_GROUP.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String updatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_SUB_GROUP.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private Date updatedTime;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column KG_EDIT_ENTITY.ENABLED
    *
    * @mbg.generated Mon Aug 03 13:27:33 CST 2020
    */
   private String enable;
   
   private String myEdit;//自己是否有修改过
   
   private String curUser;//当前查询用户

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column KG_EDIT_ENTITY.DELETED
    *
    * @mbg.generated Mon Aug 03 13:27:33 CST 2020
    */
   private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_SUB_GROUP.NAME
     *
     * @return the value of KG_SUB_GROUP.NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_SUB_GROUP.NAME
     *
     * @param name the value for KG_SUB_GROUP.NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_SUB_GROUP.REMARK
     *
     * @return the value of KG_SUB_GROUP.REMARK
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_SUB_GROUP.REMARK
     *
     * @param remark the value for KG_SUB_GROUP.REMARK
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_SUB_GROUP.CREATED_USER
     *
     * @return the value of KG_SUB_GROUP.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_SUB_GROUP.CREATED_USER
     *
     * @param createdUser the value for KG_SUB_GROUP.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_SUB_GROUP.CREATED_TIME
     *
     * @return the value of KG_SUB_GROUP.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_SUB_GROUP.CREATED_TIME
     *
     * @param createdTime the value for KG_SUB_GROUP.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_SUB_GROUP.UPDATED_USER
     *
     * @return the value of KG_SUB_GROUP.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_SUB_GROUP.UPDATED_USER
     *
     * @param updatedUser the value for KG_SUB_GROUP.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_SUB_GROUP.UPDATED_TIME
     *
     * @return the value of KG_SUB_GROUP.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_SUB_GROUP.UPDATED_TIME
     *
     * @param updatedTime the value for KG_SUB_GROUP.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

	public String getEnable() {
		return enable;
	}

	public void setEnabled(String enable) {
		this.enable = enable;
	}

	public String getDeleted() {
		return deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public String getMyEdit() {
		return myEdit;
	}

	public void setMyEdit(String myEdit) {
		this.myEdit = myEdit;
	}

	public String getCurUser() {
		return curUser;
	}

	public void setCurUser(String curUser) {
		this.curUser = curUser;
	}
}