package com.kxjl.admin.persistence.entity;

import java.util.Date;

public class KgVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_VERSION.ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_VERSION.NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_VERSION.VERSION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_VERSION.TYPE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_VERSION.REMARK
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_VERSION.BRANCH_STATUS
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String branchStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_VERSION.TRUNK_STATUS
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String trunkStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_VERSION.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_VERSION.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_VERSION.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private String updatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KG_VERSION.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_VERSION.ID
     *
     * @return the value of KG_VERSION.ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_VERSION.ID
     *
     * @param id the value for KG_VERSION.ID
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_VERSION.NAME
     *
     * @return the value of KG_VERSION.NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_VERSION.NAME
     *
     * @param name the value for KG_VERSION.NAME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_VERSION.VERSION
     *
     * @return the value of KG_VERSION.VERSION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_VERSION.VERSION
     *
     * @param version the value for KG_VERSION.VERSION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_VERSION.TYPE
     *
     * @return the value of KG_VERSION.TYPE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_VERSION.TYPE
     *
     * @param type the value for KG_VERSION.TYPE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_VERSION.REMARK
     *
     * @return the value of KG_VERSION.REMARK
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_VERSION.REMARK
     *
     * @param remark the value for KG_VERSION.REMARK
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_VERSION.BRANCH_STATUS
     *
     * @return the value of KG_VERSION.BRANCH_STATUS
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getBranchStatus() {
        return branchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_VERSION.BRANCH_STATUS
     *
     * @param branchStatus the value for KG_VERSION.BRANCH_STATUS
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setBranchStatus(String branchStatus) {
        this.branchStatus = branchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_VERSION.TRUNK_STATUS
     *
     * @return the value of KG_VERSION.TRUNK_STATUS
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getTrunkStatus() {
        return trunkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_VERSION.TRUNK_STATUS
     *
     * @param trunkStatus the value for KG_VERSION.TRUNK_STATUS
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setTrunkStatus(String trunkStatus) {
        this.trunkStatus = trunkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_VERSION.CREATED_USER
     *
     * @return the value of KG_VERSION.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_VERSION.CREATED_USER
     *
     * @param createdUser the value for KG_VERSION.CREATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_VERSION.CREATED_TIME
     *
     * @return the value of KG_VERSION.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_VERSION.CREATED_TIME
     *
     * @param createdTime the value for KG_VERSION.CREATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_VERSION.UPDATED_USER
     *
     * @return the value of KG_VERSION.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_VERSION.UPDATED_USER
     *
     * @param updatedUser the value for KG_VERSION.UPDATED_USER
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KG_VERSION.UPDATED_TIME
     *
     * @return the value of KG_VERSION.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KG_VERSION.UPDATED_TIME
     *
     * @param updatedTime the value for KG_VERSION.UPDATED_TIME
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}