package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgDataLog;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgDataLogMapper {
   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_LOG
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_LOG
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int insert(KgDataLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_LOG
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int insertSelective(KgDataLog record);

 

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_LOG
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    KgDataLog selectByPrimaryKey(String id);

  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_LOG
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int updateByPrimaryKeySelective(KgDataLog record);

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_LOG
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int updateByPrimaryKey(KgDataLog record);
}