package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgDataAuditLog;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgDataAuditLogMapper {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_LOG
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_LOG
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int insert(KgDataAuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_LOG
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int insertSelective(KgDataAuditLog record);

 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_LOG
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    KgDataAuditLog selectByPrimaryKey(String id);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_LOG
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int updateByPrimaryKeySelective(KgDataAuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_LOG
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int updateByPrimaryKey(KgDataAuditLog record);
}