package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgDataAuditDetail;
import com.kxjl.admin.persistence.entity.KgDataAuditDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgDataAuditDetailMapper {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_DETAIL
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_DETAIL
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int insert(KgDataAuditDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_DETAIL
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int insertSelective(KgDataAuditDetail record);

   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_DETAIL
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    KgDataAuditDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_DETAIL
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") KgDataAuditDetail record, @Param("example") KgDataAuditDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_DETAIL
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int updateByExample(@Param("record") KgDataAuditDetail record, @Param("example") KgDataAuditDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_DETAIL
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int updateByPrimaryKeySelective(KgDataAuditDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DATA_AUDIT_DETAIL
     *
     * @mbg.generated Wed Aug 05 15:19:24 CST 2020
     */
    int updateByPrimaryKey(KgDataAuditDetail record);
}