package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgDirTree;
import com.kxjl.admin.persistence.entity.KgDirTreeExample;
import com.kxjl.admin.persistence.entity.KgDirTreeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgDirTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DIR_TREE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    long countByExample(KgDirTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DIR_TREE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int deleteByExample(KgDirTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DIR_TREE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int deleteByPrimaryKey(KgDirTreeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DIR_TREE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int insert(KgDirTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DIR_TREE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int insertSelective(KgDirTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DIR_TREE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    List<KgDirTree> selectByExample(KgDirTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DIR_TREE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    KgDirTree selectByPrimaryKey(KgDirTreeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DIR_TREE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") KgDirTree record, @Param("example") KgDirTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DIR_TREE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByExample(@Param("record") KgDirTree record, @Param("example") KgDirTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DIR_TREE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByPrimaryKeySelective(KgDirTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_DIR_TREE
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByPrimaryKey(KgDirTree record);
}