package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgEditProperty;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgEditPropertyMapper {
   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_PROPERTY
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_PROPERTY
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int insert(KgEditProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_PROPERTY
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int insertSelective(KgEditProperty record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_PROPERTY
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    KgEditProperty selectByPrimaryKey(String id);

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_PROPERTY
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int updateByPrimaryKeySelective(KgEditProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_PROPERTY
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int updateByPrimaryKey(KgEditProperty record);
}