package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgEditRelation;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgEditRelationMapper {
   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_RELATION
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_RELATION
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int insert(KgEditRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_RELATION
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int insertSelective(KgEditRelation record);

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_RELATION
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    KgEditRelation selectByPrimaryKey(String id);

    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_RELATION
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int updateByPrimaryKeySelective(KgEditRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_RELATION
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int updateByPrimaryKey(KgEditRelation record);
}