package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgEditDirTree;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgEditDirTreeMapper {
   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_DIR_TREE
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_DIR_TREE
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int insert(KgEditDirTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_DIR_TREE
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int insertSelective(KgEditDirTree record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_DIR_TREE
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    KgEditDirTree selectByPrimaryKey(String id);

   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_DIR_TREE
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int updateByPrimaryKeySelective(KgEditDirTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_DIR_TREE
     *
     * @mbg.generated Mon Aug 03 13:27:33 CST 2020
     */
    int updateByPrimaryKey(KgEditDirTree record);
}