package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgEditClass;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgEditClassMapper {
   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_CLASS
     *
     * @mbg.generated Mon Aug 03 13:27:34 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_CLASS
     *
     * @mbg.generated Mon Aug 03 13:27:34 CST 2020
     */
    int insert(KgEditClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_CLASS
     *
     * @mbg.generated Mon Aug 03 13:27:34 CST 2020
     */
    int insertSelective(KgEditClass record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_CLASS
     *
     * @mbg.generated Mon Aug 03 13:27:34 CST 2020
     */
    KgEditClass selectByPrimaryKey(String id);

  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_CLASS
     *
     * @mbg.generated Mon Aug 03 13:27:34 CST 2020
     */
    int updateByPrimaryKeySelective(KgEditClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_EDIT_CLASS
     *
     * @mbg.generated Mon Aug 03 13:27:34 CST 2020
     */
    int updateByPrimaryKey(KgEditClass record);

}