package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgEntity;
import com.kxjl.admin.persistence.entity.KgEntityExample;
import com.kxjl.admin.persistence.entity.KgEntityKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface KgEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    long countByExample(KgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    int deleteByExample(KgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    int deleteByPrimaryKey(KgEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    int insert(KgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    int insertSelective(KgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    List<KgEntity> selectByExample(KgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    KgEntity selectByPrimaryKey(KgEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") KgEntity record, @Param("example") KgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    int updateByExample(@Param("record") KgEntity record, @Param("example") KgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    int updateByPrimaryKeySelective(KgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_ENTITY
     *
     * @mbg.generated Mon Jun 22 09:29:11 CST 2020
     */
    int updateByPrimaryKey(KgEntity record);
}