package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgKeyValue;
import com.kxjl.admin.persistence.entity.KgKeyValueExample;
import com.kxjl.admin.persistence.entity.KgKeyValueKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface KgKeyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    long countByExample(KgKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    int deleteByExample(KgKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    int deleteByPrimaryKey(KgKeyValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    int insert(KgKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    int insertSelective(KgKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    List<KgKeyValue> selectByExampleWithBLOBs(KgKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    List<KgKeyValue> selectByExample(KgKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    KgKeyValue selectByPrimaryKey(KgKeyValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") KgKeyValue record, @Param("example") KgKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") KgKeyValue record, @Param("example") KgKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    int updateByExample(@Param("record") KgKeyValue record, @Param("example") KgKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    int updateByPrimaryKeySelective(KgKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(KgKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_KEY_VALUE
     *
     * @mbg.generated Mon Jun 22 10:03:34 CST 2020
     */
    int updateByPrimaryKey(KgKeyValue record);
}