package com.kxjl.admin.persistence.dao;


import com.kxjl.admin.persistence.entity.KgObjectSubGroup;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgObjectSubGroupMapper {
   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int deleteByPrimaryKey(KgObjectSubGroup key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int insertSelective(KgObjectSubGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    KgObjectSubGroup selectByPrimaryKey(KgObjectSubGroup key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByPrimaryKeySelective(KgObjectSubGroup record);

}