package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgObjectProperty;
import com.kxjl.admin.persistence.entity.KgObjectPropertyExample;
import com.kxjl.admin.persistence.entity.KgObjectPropertyKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgObjectPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    long countByExample(KgObjectPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int deleteByExample(KgObjectPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int deleteByPrimaryKey(KgObjectPropertyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int insert(KgObjectProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int insertSelective(KgObjectProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    List<KgObjectProperty> selectByExample(KgObjectPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    KgObjectProperty selectByPrimaryKey(KgObjectPropertyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") KgObjectProperty record, @Param("example") KgObjectPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByExample(@Param("record") KgObjectProperty record, @Param("example") KgObjectPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByPrimaryKeySelective(KgObjectProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByPrimaryKey(KgObjectProperty record);
}