package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgObjectRelation;
import com.kxjl.admin.persistence.entity.KgObjectRelationExample;
import com.kxjl.admin.persistence.entity.KgObjectRelationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgObjectRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    long countByExample(KgObjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int deleteByExample(KgObjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int deleteByPrimaryKey(KgObjectRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int insert(KgObjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int insertSelective(KgObjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    List<KgObjectRelation> selectByExample(KgObjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    KgObjectRelation selectByPrimaryKey(KgObjectRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") KgObjectRelation record, @Param("example") KgObjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByExample(@Param("record") KgObjectRelation record, @Param("example") KgObjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByPrimaryKeySelective(KgObjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_OBJECT_RELATION
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByPrimaryKey(KgObjectRelation record);
}