package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgProperty;
import com.kxjl.admin.persistence.entity.KgPropertyExample;
import com.kxjl.admin.persistence.entity.KgPropertyKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    long countByExample(KgPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int deleteByExample(KgPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int deleteByPrimaryKey(KgPropertyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int insert(KgProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int insertSelective(KgProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    List<KgProperty> selectByExample(KgPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    KgProperty selectByPrimaryKey(KgPropertyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") KgProperty record, @Param("example") KgPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByExample(@Param("record") KgProperty record, @Param("example") KgPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByPrimaryKeySelective(KgProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_PROPERTY
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByPrimaryKey(KgProperty record);
}