package com.kxjl.admin.persistence.dao;

import com.kxjl.admin.persistence.entity.KgSubGroup;
import com.kxjl.admin.persistence.entity.KgSubGroupExample;
import com.kxjl.admin.persistence.entity.KgSubGroupKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KgSubGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_SUB_GROUP
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    long countByExample(KgSubGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_SUB_GROUP
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int deleteByExample(KgSubGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_SUB_GROUP
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int deleteByPrimaryKey(KgSubGroupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_SUB_GROUP
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int insert(KgSubGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_SUB_GROUP
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int insertSelective(KgSubGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_SUB_GROUP
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    List<KgSubGroup> selectByExample(KgSubGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_SUB_GROUP
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    KgSubGroup selectByPrimaryKey(KgSubGroupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_SUB_GROUP
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") KgSubGroup record, @Param("example") KgSubGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_SUB_GROUP
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByExample(@Param("record") KgSubGroup record, @Param("example") KgSubGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_SUB_GROUP
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByPrimaryKeySelective(KgSubGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KG_SUB_GROUP
     *
     * @mbg.generated Tue Jun 16 16:31:55 CST 2020
     */
    int updateByPrimaryKey(KgSubGroup record);
}